[workspace]
members = [
    "crates/api_decl",
    "crates/api_server",
    "crates/cli",
    "crates/config",
    "crates/core",
    "crates/types",
]
resolver = "2"

[profile.dev]
debug = 0

[profile.release]
strip = "debuginfo" # Automatically strip symbols from the binary.
lto = "thin"        # Enable link-time optimization.

[workspace.package]
version = "0.2.5" # x-release-please-version
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/anvil-zksync"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[workspace.dependencies]
#########################
# ZKsync dependencies  #
#########################
zksync_multivm = { git = "https://github.com/matter-labs/zksync-era.git", rev = "core-v25.4.0" }
zksync_contracts = { git = "https://github.com/matter-labs/zksync-era.git", rev = "core-v25.4.0" }
zksync_types = { git = "https://github.com/matter-labs/zksync-era.git", rev = "core-v25.4.0" }
zksync_vm_interface = { git = "https://github.com/matter-labs/zksync-era.git", rev = "core-v25.4.0" }
zksync_web3_decl = { git = "https://github.com/matter-labs/zksync-era.git", rev = "core-v25.4.0", features = [
    "server",
] }

#########################
# External dependencies #
#########################
anyhow = "1.0"
alloy-signer-local = { version = "0.5.4", features = ["mnemonic"] }
alloy-signer = { version = "0.5.4", default-features = false }
async-trait = "0.1.85"
chrono = { version = "0.4.31", default-features = false }
clap = { version = "4.2.4", features = ["derive", "env"] }
colored = "2"
ethabi = "16.0.0"
eyre = "0.6"
flate2 = "1.0"
futures = { version = "0.3", features = ["compat"] }
hex = "0.4"
http = "1.1.0"
indexmap = "2.0.1"
itertools = "0.13"
jsonrpsee = "0.23"
lazy_static = "1.4"
once_cell = "1.7"
rand = "0.8"
reqwest = { version = "0.11", features = ["blocking"] }
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"
time = "0.3.36"
tokio = { version = "1", features = ["full", "tracing"] }
tower = "0.4"
tower-http = { version = "0.6.2", features = ["cors"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
    "time",
    "json",
    "local-time",
] }

#########################
# Test dependencies    #
#########################
httptest = "0.15.4"
tempdir = "0.3.7"
maplit = "1.0.2"
zksync-web3-rs = "0.1.1"
ethers = { version = "2.0.4", features = ["rustls"] }
test-case = "3.3.1"
backon = "1.3.0"

#########################
# Local dependencies    #
#########################
anvil_zksync_api_decl = { path = "crates/api_decl" }
anvil_zksync_api_server = { path = "crates/api_server" }
anvil_zksync_config = { path = "crates/config" }
anvil_zksync_core = { path = "crates/core" }
anvil_zksync_types = { path = "crates/types" }
